# Web Dockerfile
ARG BASE_IMAGE

FROM ${BASE_IMAGE}

COPY ./compose/fastapi-celery/celery/beat/start /start-beat
RUN sed -i 's/\r$//g' /start-beat
RUN chmod +x /start-beat
RUN chown fastapi /start-beat

RUN mkdir /app
WORKDIR /app

# copy project code
COPY . .

RUN chown -R fastapi:fastapi /app

USER fastapi

CMD ["/start-beat"]
