FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN echo "alias python='python3'" >> /root/.bashrc

EXPOSE 8000

#WORKDIR /app/api

#CMD ["uvicorn", "main:app", "--host=0.0.0.0" , "--reload" , "--port", "8000"]
CMD ["bash"]