FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN echo "alias python='python3'" >> /root/.bashrc

COPY . .

ENV PYTHONPATH=/app/api

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host=0.0.0.0", "--port=8000", "--reload"]