# Web Dockerfile
ARG BASE_IMAGE

FROM ${BASE_IMAGE}


COPY ./compose/fastapi-celery/celery/flower/start /start-flower
RUN sed -i 's/\r$//g' /start-flower
RUN chmod +x /start-flower
RUN chown fastapi /start-flower

RUN mkdir /app
WORKDIR /app

# copy project code
COPY . .

RUN chown -R fastapi:fastapi /app

USER fastapi

CMD ["/start-flower"]
