FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENV PYTHONPATH=/app/inference

CMD ["celery", "-A", "inference.worker.celery", "worker", "--loglevel=info"]