# Web Dockerfile
ARG BASE_IMAGE

FROM ${BASE_IMAGE}

COPY ./compose/fastapi-celery/celery/entrypoint-celery /entrypoint-celery
RUN sed -i 's/\r$//g' /entrypoint-celery
RUN chmod +x /entrypoint-celery
RUN chown fastapi /entrypoint-celery


COPY ./compose/fastapi-celery/celery/worker/start /start-worker
RUN sed -i 's/\r$//g' /start-worker
RUN chmod +x /start-worker
RUN chown fastapi /start-worker

COPY ./compose/fastapi-celery/celery/worker/requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

RUN mkdir /app
WORKDIR /app

# copy project code
COPY . .

RUN chown -R fastapi:fastapi /app

USER fastapi

ENTRYPOINT ["/entrypoint-celery"]
CMD ["/start-worker"]
