# Web Dockerfile
ARG BASE_IMAGE

FROM ${BASE_IMAGE}


COPY ./compose/fastapi-celery/celery/worker/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start
RUN chown fastapi /start

RUN mkdir /app
WORKDIR /app

# copy project code
COPY . .

RUN chown -R fastapi:fastapi /app

USER fastapi

