# Web Dockerfile
ARG BASE_IMAGE

FROM ${BASE_IMAGE}

COPY ./compose/fastapi-celery/web/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint
RUN chown fastapi /entrypoint

COPY ./compose/fastapi-celery/web/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start
RUN chown fastapi /start

RUN mkdir -p /app/alembic/versions
RUN chmod -R 777 /app/alembic/versions

WORKDIR /app

# copy project code
COPY . .

RUN chown -R fastapi:fastapi /app
RUN chmod -R 777 /app

USER fastapi

ENTRYPOINT ["/entrypoint"]